FROM node:alpine

WORKDIR /repo
COPY package*.json ./
COPY lerna.json ./

RUN npm install
COPY packages/api/package*.json ./packages/api/
COPY packages/web_app ./packages/web_app/
COPY packages/common/package*.json ./packages/common/

RUN npx lerna bootstrap

COPY . .

RUN npx lerna run build

CMD ["true"]
